import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next with tailwing',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className} h-screen bg-white `}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
